
services:
  nginx:
    networks:
      - my_network
    image: nginx:latest
    environment:
      - TZ=America/Los_Angeles
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/index.html:/usr/share/nginx/html/index.html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /home/loic/.acme.sh/loic.lescoat.me_ecc/fullchain.cer:/ssl/fullchain.pem # TODO don't hardcode
      - /home/loic/.acme.sh/loic.lescoat.me_ecc/loic.lescoat.me.key:/ssl/privkey.pem
    restart: unless-stopped
  youtube-to-mp3:
    networks:
      - my_network
    build:
      context: ./youtube-to-mp3
      args:
        PORT: 8002
    container_name: youtube-to-mp3
    working_dir: /deploy
    restart: unless-stopped
networks:
  my_network:
    driver: bridge

configs:
  nginx_conf:
    file: ./nginx/nginx.conf
