server {
    listen 0.0.0.0:80;
    listen [::]:80;
    client_max_body_size 100M;

    server_name raspberrypi.local;

    location /youtube-to-mp3/ {
        proxy_pass http://localhost:8002/youtube-to-mp3/; # of form: http://service_name:port/path
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

	# auth_basic "Restricted Access";
        # auth_basic_user_file /etc/nginx/.htpasswd;
    }
    location /thundershare/ {
	allow 192.168.50.0/24;
        allow fe80::/10;
	deny all;              # Deny access from all other IPs
        proxy_pass http://localhost:8000/thundershare/; # of form: http://service_name:port/path
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    location /iptest/ {
        return 200 "$remote_addr\n";
    }

    root /usr/share/nginx/html;
    index index.html;
}
